version: '3.9'

services:
  langbuddy-rabbitmq:
    image: rabbitmq:management
    container_name: langbuddy-rabbitmq
    hostname: rabbitmq
    restart: always
    volumes:
      - ./RabbitMq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - langbaddy-deb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  langbaddy-db:
    image: postgres:latest
    restart: always
    container_name: 'langbaddy-db'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: LangBuddy.Develop
    ports:
      - 10001:5432
    networks:
      - langbaddy-deb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  langbuddy-cache-data:
    container_name: 'langbuddy-cache-data'
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
      - cache:/data
    networks:
      - langbaddy-deb
    # environment:
    #   - REDIS_PASSWORD=my-password
    #   - REDIS_PORT=6379
    #   - REDIS_DATABASES=16

  langbaddy-data-access:
    container_name: 'langbaddy-data-access'
    depends_on:
      - 'langbaddy-db'
    build:
      dockerfile: ./DataAccess/Dockerfile
      context: ./DataAccess
    deploy:
      resources:
        limits:
          memory: 1024M
    ports:
      - 8010:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LOGS_PATH=/var/log/langbaddy-data-access
    networks:
      - langbaddy-deb

  langbaddy-chat-data:
      container_name: 'langbaddy-chat-data'
      depends_on:
        - 'langbaddy-db'
        - 'langbuddy-cache-data'
      build:
        dockerfile: ./Web/Dockerfile
        context: ./ChatData
      deploy:
        resources:
          limits:
            memory: 1024M
      ports:
        - 8009:80
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - LOGS_PATH=/var/log/langbaddy-chat-data
      networks:
        - langbaddy-deb
      
  langbaddy-authentication:
    container_name: 'langbaddy-authentication'
    build:
      dockerfile: ./Authentication/Dockerfile
      context: ./Authentication
    deploy:
      resources:
        limits:
          memory: 1024M
    ports:
      - 8002:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LOGS_PATH=/var/log/langbaddy-authentication
    networks:
      - langbaddy-deb

  email-sender:
    container_name: 'email-sender'
    build:
      dockerfile: ./Dockerfile
      context: ./LangBuddy.EmailSending
    deploy:
      resources:
        limits:
          memory: 2048M
    ports:
      - 80:8015
    environment:
      - LOGS_PATH=/var/log/dev-email-sender
      - MAIL_HOST=smtp.gmail.com
      - MAIL_USER=lang.buddy.official@gmail.com
      - MAIL_PASSWORD=jzfagybcionxninc
      - MAIL_FROM=lang.buddy.official@gmail.com

      - MAIL_TRANSPORT=smtp://lang.buddy.official@gmail.com:jzfagybcionxninc@smtp.gmail.com
    networks:
      - langbaddy-deb

  consumer-1:
      container_name: 'consumer-1'
      build:
        dockerfile: ./Dockerfile
        context: ./Consumer
      deploy:
        resources:
          limits:
            memory: 1024M
      ports:
        - 8019:80
      # depends_on:
        # - email-sender
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - LOGS_PATH=/var/log/dev-consumer
      networks:
        - langbaddy-deb

  langbaddy-gate-way:
    container_name: 'langbaddy-gate-way'
    depends_on:
      - 'langbaddy-db'
    build:
      dockerfile: ./Web/Dockerfile
      context: ./GateWay
    deploy:
      resources:
        limits:
          memory: 1024M
    ports:
      - 8001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LOGS_PATH=/var/log/langbaddy-gate-way
    networks:
      - langbaddy-deb

volumes:
  postgres-data:
  cache:

networks:
  langbaddy-deb: {
    driver: bridge
  }